---
- name: Create NGINX docker directory
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    state: directory
    mode: "0750"
  loop:
    - "{{ nginx_docker_path }}"
    - "{{ nginx_docker_path }}/conf.d"
    - "{{ nginx_docker_path }}/ssl"

- name: Create NGINX docker default configuration
  ansible.builtin.copy:
    content: "{{ nginx_docker_default_config }}"
    dest: "{{ nginx_docker_path }}/conf.d/default.conf"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  notify: restart nginx

- name: Manage NGINX docker custom configuration
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ nginx_docker_path }}/conf.d/{{ item.name }}"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  loop: "{{ nginx_docker_config }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_docker_config is defined
    - nginx_docker_config | length
  notify: restart nginx

- name: Manage NGINX docker custom certificates
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ nginx_docker_path }}/ssl/{{ item.name }}"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0600"
  loop: "{{ nginx_docker_certs }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - nginx_docker_certs is defined
    - nginx_docker_certs | length
  notify: restart nginx

- name: Manage NGINX docker compose configuration
  ansible.builtin.template:
    src: compose.yaml.j2
    dest: "{{ nginx_docker_path }}/compose.yaml"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  notify: restart nginx

- name: Manage NGINX docker compose override configuration
  ansible.builtin.template:
    src: compose.override.yaml.j2
    dest: "{{ nginx_docker_path }}/compose.override.yaml"
    owner: "{{ nginx_docker_owner }}"
    group: "{{ nginx_docker_group }}"
    mode: "0640"
  when:
    - nginx_docker_compose_override is defined
    - nginx_docker_compose_override | length
  notify: restart nginx

- name: Validate NGINX docker compose deployment
  ansible.builtin.command:
    cmd: docker compose config --quiet
    chdir: "{{ nginx_docker_path }}"
  changed_when: false

- name: Start NGINX docker compose deployment
  ansible.builtin.command:
    cmd: docker compose --ansi never --progress plain up --detach
    chdir: "{{ nginx_docker_path }}"
  register: nginx_docker_
  changed_when: "'Started' in nginx_docker_.stdout"
